function getVerbes(){
	return [ ["être","shi"],
			 ["avoir","yǒu"],
			 ["ne pas avoir","méi yǒu"],
			 ["manger","chī"],
			 ["boire","hē"],
			 ["regarder","kàn"],
			 ["jeter un oeil","kàn-kan"],
			 ["aller","qù"],
			 ["comprendre","dǒng"],
			 ["savoir/avoir connaissance","zhīdào"],
			 ["aimer","ài"],
			 ["apprécier","xihuān"],
			 ["vouloir","yào"],
			 ["offrir","sòng"],
			 ["inviter","qǐng"],
			 ["avoir envie/vouloir","xiāng"],
			 ["acheter","mǎi"],
			 ["habiter","zhù"],
			 ["venir (provenance)","cóng"],
			 ["traverser","guò"],
			 ["travailler","zuò"],
			 ["travailler-comme","dang-guo"]
			 ]
}